version: '3.7'


services:
  django_app:
    build:
      context: .
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my_network
    restart: always
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - my_network
    restart: always
volumes:
  static:
networks:
  my_network: